name: actions-ctf-chall-status-generator
on: [push, pull_request]

jobs:
  generate:
    name: generate README
    runs-on: ubuntu-latest
    steps:
      - name: Download ctf-chall-status-generator
        run: cargo install --git https://github.com/yu1hpa/ctf-chall-status-generator.git
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: ctf-chall-status-generator --dir-path ./sample-data
      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}