name: actions-ctf-chall-status-generator
on: [pull_request]
env:
  WORKDIR: ./sample-data

jobs:
  generate:
    name: generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Download ctf-chall-status-generator
        run: cargo install --git https://github.com/yu1hpa/ctf-chall-status-generator.git
      - name: Generate TESTED.md
        run: ctf-chall-status-generator --dir-path $WORKDIR
      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add "$WORKDIR/TESTED.md"
          git commit -m "chore(auto-commit): Update TESTED.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.head_ref }}
